package base.entities;
// Generated Feb 2, 2018 11:45:13 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImportDetailId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ImportDetailId implements java.io.Serializable {

	private int importId;
	private int productId;

	public ImportDetailId() {
	}

	public ImportDetailId(int importId, int productId) {
		this.importId = importId;
		this.productId = productId;
	}

	@Column(name = "ImportID", nullable = false)
	public int getImportId() {
		return this.importId;
	}

	public void setImportId(int importId) {
		this.importId = importId;
	}

	@Column(name = "ProductID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImportDetailId))
			return false;
		ImportDetailId castOther = (ImportDetailId) other;

		return (this.getImportId() == castOther.getImportId()) && (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImportId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
