package base.entities;
// Generated Feb 2, 2018 11:45:13 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Logs generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Logs", catalog = "HighTechStore")
public class Logs implements java.io.Serializable {

	private int id;
	private String description;

	public Logs() {
	}

	public Logs(int id, String description) {
		this.id = id;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Description", nullable = false, length = 1073741823)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
